### ISSUE TITLE
Recaptcha Required

### ISSUE THREAD

**Issue by moshfeu** [VividCortex/angular-recaptcha#131]
It will be helpful if will mention that the `div` act like input and you can validate the captcha using `ng-required`.

For example:

    <form name="yourForm">
        <div name="captcha" class="form-control height-auto" data-vc-recaptcha="" data-key="'captcha-key'" data-ng-model="model.captcha" data-ng-required="true"></div>
    </form>

Then, you can show an error message if it invalid, something like:

    <div data-ng-show="yourForm.captcha.$invalid">No valid</div>

**Comment by TheSharpieOne** [comment]
There shouldn't be any need for that required attribute. It being required is an opt-out feature instead of opt-in as for most use cases the developer requires the captcha to be valid/checked (and to prevent breaking change). #96 kinda has some information about this and #107 adds the ability to opt-out. By default, the required validation will happen, as mentioned in [the readme](https://github.com/VividCortex/angular-recaptcha#form-validation), when you place it within a named form (the name attribute triggers it to become a formControl, which is used for the form state/validation).

**Comment by moshfeu** [comment]
Your are right. My bad..
