### ISSUE TITLE
Is there a way to reset the captcha

### ISSUE THREAD

**Issue by dsouzaalfred** [VividCortex/angular-recaptcha#153]
Hi, is there a way to reset the captcha.
Suppose my username and password validation fails, I would like to reset the captcha.

**Comment by TheSharpieOne** [comment]
It doesn't seem to be documented in the readme, but there is a reload method on the service which accepts the widgetId for the recaptcha instance you are trying to reset.
Here is a basic example:
```
myAngularAppRef.controller('myFormCtrlWhatever', function($scope, $http, vcRecaptchaService){
  var widgetId;
  $scope.myReCaptchaKey = '23o432k23ojofj23orjo2fjo2j23'; // Your actual public key.

  $scope.submitForm = function(formValues) {
    return $http.post('/whatever/login', formValues)
      .then(function(resp){
         // All is good, move on
      })
      .catch(function(resp){
        // Oh noes!
        vcRecaptchaService.reload(widgetId);
      });
  };

  // Get the widgetId when the recaptcha instance is created via onCreate callback
  $scope. onWidgetCreate = function(_widgetId){
    widgetId = _widgetId;
  };
})
```
The directive would need to have the onCreate attribute set to the callback function
```
<div
    vc-recaptcha
    key="myReCaptchaKey"
    ng-model="gRecaptchaResponse"
    on-create="onWidgetCreate(widgetId)"
></div>
```

Note: this is a basic example, there are other ways to do this and best practices which are not used in order to make the example more simple.

**Comment by dackmin** [comment]
Works as a charm, should be documented.

**Comment by dsouzaalfred** [comment]
Thanks @TheSharpieOne this works.
Agree with @dackmin this should be documented.
