### ISSUE TITLE
Widget doesn't appear on page load

### ISSUE THREAD

**Issue by harshithkashyap** [VividCortex/angular-recaptcha#36]
I have followed the same guide as in the demo. The recaptcha widget isn't being displayed as soon as the page loads. Only after i submit the form data, the widget appears and calls respective methods(setResponse).
<pre>angular-recaptcha build:2015-01-09 </pre>
<pre>
<b>div</b> 
    vc-recaptcha 
    theme="'dark'"
    key="model.key"
    on-create="setWidgetId(widgetId)" 
    on-success="setResponse(response)" 
<b>/div </b>
</pre>

I'm also facing a lot problem with the server validation. The npm recaptcha projects seems to be outdated. Are there any documentation/guide towards the same?

**Comment by TheSharpieOne** [comment]
For node side, I use https://github.com/np-maintain/simple-recaptcha-new  It works great.

Also, try updating to the latest release `build: 2015-02-08` and see if that resolves any problems (note: vcRecaptchaApiLoaded previously had a typo and has been fixed in the latest code, you'll need to change that in your recaptch script URL). If not, can you post more of your code?

**Comment by Mctalian** [comment]
@harshithkashyap, @TheSharpieOne seems to be correct. It is definitely the rename from "vc**Recaptha**ApiLoaded" to "vc**Recaptcha**ApiLoaded" (notice the c was missing in the first one).

Make sure your Google ReCaptcha API HTML script tag is now:

```<script src='//www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit' async defer></script>```

**Comment by PaulMougel** [comment]
I was bashing my head against this!
Thank you @Mctalian, renaming `onload=vcRecapthaApiLoaded` to `onload=vcRecaptchaApiLoaded`  in the HTML fixed the issue.

**Comment by waqas10075** [comment]
@PaulMougel  can you please share your HTML code so I can fix mine?
