### ISSUE TITLE
reCaptcha callback when finished loading.

### ISSUE THREAD

**Issue by sboisse** [VividCortex/angular-recaptcha#4]
You are using a timeout of 1000ms as a workaround for not knowing when the captcha is finished loading, but you can actually provide that callback in the options of the reCaptcha.create() call.

See: https://developers.google.com/recaptcha/docs/display#recaptcha_methods

and read the remarks for the create() function.

**Comment by RobzInadE** [comment]
Hello

Any updates here? I seem to have my captcha flicker away all the time. (I'm guessing it doesn't load within the timeout wait of 1s.)

This is not viable for many of my customers.
Regards

**Comment by mtrias** [comment]
@RobzInadE This issue is very old and is about captcha v1. We updated the library to use the new Google recaptcha a while ago in 2.0, so this thread doesn't apply to the latest release of the library. 

If you are having problems with the latest release, then is surely not related to this thread so please open a new issue in this repo.

Thanks.
