### ISSUE TITLE
setWidgetId method

### ISSUE THREAD

**Issue by ssameer07** [VividCortex/angular-recaptcha#77]
Firstly Awesome directive...
I am using angular-recaptcha and i want to multiple widgets in an single application....
As told in documentation i used setWidgetId('widget1'); but in the console i got an error as invalid client Id....
Can u please share a fiddle or plunker explaining how to render multiple widgets using this directive..

Thanks,waiting for ur response...
sam....

**Comment by jackkum** [comment]
Here is the same question: https://github.com/VividCortex/angular-recaptcha/issues/76
http://plnkr.co/edit/r6msW5sXV7QzoWIwxY28?p=preview

**Comment by TheSharpieOne** [comment]
The documentation which uses `setWidgetId` is not documenting `setWidgetId`, but showing how one would use the `on-create` listener to listen for the create event which will provide the ability to get the widgetId (created by recaptcha).  The `setWidgetId` in [the example](https://github.com/VividCortex/angular-recaptcha#example) is a custom function allowing the developer to store the id (created by recaptcha, passed through the listener callback) for future use.

You do not get to set the ID of the widget, but you can get and set/store the value so that you can reference specific widgets when there are multiple of them.

**Comment by ssameer07** [comment]
why the plunker u shared is not displaying recaptcha???

**Comment by jackkum** [comment]
@ssameer07 Sorry, try now http://plnkr.co/edit/r6msW5sXV7QzoWIwxY28?p=preview

you're can do that:
```javascript
$scope.response1 = '';

$scope.submit = funtion()
{
  if($scope.response1.length === 0){
    $scope.alerts = [ { type: 'danger', msg: 'Please complete the captcha.' } ];
    return;
  }
}
```

**Comment by ssameer07** [comment]
@jackkum  wooooh...that worked for me...
it took ma whole day solving this....thanks a lot man!!!
